### ISSUE TITLE
Booklist Frontend Integration

### ISSUE THREAD

**Issue by antoniolinhart** [STEP-Pod-Capstone-Project/Capstone-Project#36]
**Add booklist to frontend**

- Implement page to show a list of user's booklists
- Implement page to show details of a user's booklists
- Page to create a booklist

**Comment by MauroGuerrero20** [comment]
> **Add booklist to frontend**
> 
> * Implement page to show a list of user's booklists
> * Implement page to show details of a user's booklists
> * Page to create a booklist

https://github.com/STEP-Pod-Capstone-Project/Capstone-Project/pull/54 Implements all of these features.

Is there any other basic Frontend implementations I should do for BookLists
